Minor refactor to separate user commands
michaeljolley/io-twitch pull request #74
Opened 2019-08-02 03:26 UTC by CodemanCodes

This will have to be looked over and tested as my JS and TS is a bit rusty.

List of changes:

- Refactored updateUserCommand to its own user-commands file to aid in future expansion of commands (spoke of being able to set twitter/github usernames)
- Added notification to user in channel of successful or unsuccessful update
- Renamed saveUser() to updateAndGetUser() to add clarity to what the function does
- Added some error handling to the update function in user.ts.

Previously in user.ts if there was an error updating the document in mongoDB, the cache for that user would have been overwritten with undefined. Added check to see if a document was actually returned. If not, set user back to what is in cache and return the cached user.

2019-08-04 18:48 UTC, michaeljolley requested changes

2019-08-04 18:48 UTC, MichaelJolley commented on src/chat/src/twitch-chat.ts
>      for (const basicCommand of Object.values(BasicCommands)) {
Probably want to surround this for with `if (!handledByCommand) {` so we don't try and process it if we've handled it in a userCommand

2019-08-04 18:48 UTC, MichaelJolley commented on src/chat/src/commands/user-commands.ts
> +              return true;
Handled by a later return true

2019-08-04 18:48 UTC, MichaelJolley commented on src/chat/src/commands/user-commands.ts
> +              return true;
Handled by a later return true

2019-08-04 18:48 UTC, MichaelJolley commented on src/chat/src/commands/user-commands.ts
> +  ): Promise<boolean> => {
Let's return the updated IUserInfo or undefined

2019-08-04 18:48 UTC, MichaelJolley commented on src/chat/src/twitch-chat.ts
> +      handledByCommand = await userCommand(
Set the userInfo property if it came back.  And if it did, set handledByCommand = true

2019-08-04 18:48 UTC, MichaelJolley commented on src/chat/src/twitch-chat.ts
>        userInfo
Move creating the chatMessageArg to just before we emit

2019-08-04 20:27 UTC, CodemanCodes commented on src/chat/src/twitch-chat.ts
>      for (const basicCommand of Object.values(BasicCommands)) {
Fixed this

2019-08-04 20:28 UTC, CodemanCodes commented on src/chat/src/commands/user-commands.ts
> +              return true;
Fixed this, had to keep one of the returns because it returns IUserInfo instead of a boolean. Still need to keep the boolean as a return type so we can say the message wasn't handled by the command

2019-08-04 20:29 UTC, CodemanCodes commented on src/chat/src/commands/user-commands.ts
> +              return true;
Fixed this, had to keep one of the returns because it returns IUserInfo instead of a boolean. Still need to keep the boolean as a return type so we can say the message wasn't handled by the command

2019-08-04 20:30 UTC, CodemanCodes commented on src/chat/src/commands/user-commands.ts
> +  ): Promise<boolean> => {
Made return type <IUserInfo | boolean> so we can still pass along false if that command doesn't handle the message

2019-08-04 20:31 UTC, CodemanCodes commented on src/chat/src/twitch-chat.ts
> +      handledByCommand = await userCommand(
Done and done

2019-08-04 20:46 UTC, CodemanCodes commented on src/chat/src/twitch-chat.ts
>        userInfo
This I didn't do, instead I just change the referenced userInfo to what was returned. This should still be valid es6 because its not changing the object itself and I think keeps it clear that the chatMessageArg for the rest of the commands isn't dependent on the userCommands. If you'd rather have it moved let me know and I can move it

2019-08-05 04:01 UTC, michaeljolley approved these changes

2019-08-05 04:02 UTC, merged